# Generated by Django 4.2.11 on 2024-03-16 14:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='The main content of the post goes here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
