# Generated by Django 4.2.11 on 2024-03-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_on',
        ),
    ]
