# Generated by Django 4.2.11 on 2024-03-16 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
